package com.codebridge.server.dto;

import com.codebridge.server.model.enums.ServerAuthProvider;
import com.codebridge.server.model.enums.ServerCloudProvider;
import com.codebridge.server.model.enums.ServerStatus;
import java.time.LocalDateTime;
import java.util.UUID;

public class ServerResponse {
    private UUID id;
    private String name;
    private String hostname;
    private Integer port;
    private String remoteUsername;
    private ServerAuthProvider authProvider;
    // We don't include password in response
    private UUID sshKeyId; // ID of the associated SshKey
    private String sshKeyName; // Name of the associated SshKey (convenience)
    private ServerStatus status;
    private String operatingSystem;
    private ServerCloudProvider cloudProvider;
    private UUID userId; // Owner
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;

    // Constructor, Getters, Setters
    public ServerResponse() {
    }

    // Example of a full constructor, can be generated by Lombok or IDE
    public ServerResponse(UUID id, String name, String hostname, Integer port, String remoteUsername,
                          ServerAuthProvider authProvider, UUID sshKeyId, String sshKeyName, ServerStatus status,
                          String operatingSystem, ServerCloudProvider cloudProvider, UUID userId,
                          LocalDateTime createdAt, LocalDateTime updatedAt) {
        this.id = id;
        this.name = name;
        this.hostname = hostname;
        this.port = port;
        this.remoteUsername = remoteUsername;
        this.authProvider = authProvider;
        this.sshKeyId = sshKeyId;
        this.sshKeyName = sshKeyName;
        this.status = status;
        this.operatingSystem = operatingSystem;
        this.cloudProvider = cloudProvider;
        this.userId = userId;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }


    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getHostname() {
        return hostname;
    }

    public void setHostname(String hostname) {
        this.hostname = hostname;
    }

    public Integer getPort() {
        return port;
    }

    public void setPort(Integer port) {
        this.port = port;
    }

    public String getRemoteUsername() {
        return remoteUsername;
    }

    public void setRemoteUsername(String remoteUsername) {
        this.remoteUsername = remoteUsername;
    }

    public ServerAuthProvider getAuthProvider() {
        return authProvider;
    }

    public void setAuthProvider(ServerAuthProvider authProvider) {
        this.authProvider = authProvider;
    }

    public UUID getSshKeyId() {
        return sshKeyId;
    }

    public void setSshKeyId(UUID sshKeyId) {
        this.sshKeyId = sshKeyId;
    }

    public String getSshKeyName() {
        return sshKeyName;
    }

    public void setSshKeyName(String sshKeyName) {
        this.sshKeyName = sshKeyName;
    }

    public ServerStatus getStatus() {
        return status;
    }

    public void setStatus(ServerStatus status) {
        this.status = status;
    }

    public String getOperatingSystem() {
        return operatingSystem;
    }

    public void setOperatingSystem(String operatingSystem) {
        this.operatingSystem = operatingSystem;
    }

    public ServerCloudProvider getCloudProvider() {
        return cloudProvider;
    }

    public void setCloudProvider(ServerCloudProvider cloudProvider) {
        this.cloudProvider = cloudProvider;
    }

    public UUID getUserId() {
        return userId;
    }

    public void setUserId(UUID userId) {
        this.userId = userId;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }
}
