package com.codebridge.server.dto;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;

public class SshKeyRequest {

    @NotBlank(message = "Name cannot be blank")
    @Size(max = 255, message = "Name cannot exceed 255 characters")
    private String name;

    // Public key is often provided by user, private key might be generated or also provided (carefully)
    @NotBlank(message = "Public key cannot be blank")
    private String publicKey;

    // Private key is sensitive, handle with extreme care.
    // Often, for requests, you might not want to accept it directly, or only for specific import flows.
    // For this basic DTO, we'll include it, but service logic should be cautious.
    private String privateKey; // Optional, might be generated by server

    // Getters and Setters
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPublicKey() {
        return publicKey;
    }

    public void setPublicKey(String publicKey) {
        this.publicKey = publicKey;
    }

    public String getPrivateKey() {
        return privateKey;
    }

    public void setPrivateKey(String privateKey) {
        this.privateKey = privateKey;
    }
}
