// Code generated by protoc-gen-go. DO NOT EDIT.
// This is a placeholder for the generated gRPC code.
// In a real implementation, this would be generated from the proto file.

package grpc

import (
	"context"

	"github.com/codebridge/feature-flag-service/internal/model"
	"google.golang.org/grpc"
)

// FeatureFlagServiceServer is the server API for FeatureFlagService service.
type FeatureFlagServiceServer interface {
	// GetFlag gets a flag by key
	GetFlag(context.Context, *FlagRequest) (*FlagResponse, error)
	
	// GetFlags gets multiple flags by keys
	GetFlags(context.Context, *MultiFlagRequest) (*MultiFlagResponse, error)
	
	// EvaluateFlag evaluates a flag with context
	EvaluateFlag(context.Context, *FlagEvaluationRequest) (*FlagEvaluationResponse, error)
	
	// SetFlag sets a flag
	SetFlag(context.Context, *SetFlagRequest) (*SetFlagResponse, error)
	
	// StreamFlagUpdates streams flag updates
	StreamFlagUpdates(*FlagStreamRequest, FeatureFlagService_StreamFlagUpdatesServer) error
	
	// ListFlags lists flags
	ListFlags(context.Context, *ListFlagsRequest) (*ListFlagsResponse, error)
	
	// HealthCheck performs a health check
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
}

// RegisterFeatureFlagServiceServer registers the server with the gRPC server
func RegisterFeatureFlagServiceServer(s *grpc.Server, srv FeatureFlagServiceServer) {
	// In a real implementation, this would register the server
}

// FlagRequest is the request for GetFlag
type FlagRequest struct {
	FlagKey   string
	Namespace string
}

// FlagResponse is the response for GetFlag
type FlagResponse struct {
	FlagKey  string
	Exists   bool
	Metadata *FlagMetadata
	Value    interface{}
}

// FlagMetadata contains metadata about a flag
type FlagMetadata struct {
	Description string
	CreatedAt   int64
	UpdatedAt   int64
	CreatedBy   string
	UpdatedBy   string
	Version     string
	Tags        map[string]string
}

// MultiFlagRequest is the request for GetFlags
type MultiFlagRequest struct {
	FlagKeys  []string
	Namespace string
}

// MultiFlagResponse is the response for GetFlags
type MultiFlagResponse struct {
	Flags []*FlagResponse
}

// FlagEvaluationRequest is the request for EvaluateFlag
type FlagEvaluationRequest struct {
	FlagKey   string
	Namespace string
	Context   *EvaluationContext
}

// EvaluationContext is the context for flag evaluation
type EvaluationContext struct {
	UserId            string
	SessionId         string
	Attributes        map[string]string
	NumericAttributes map[string]float64
	BooleanAttributes map[string]bool
	ServiceContext    *ServiceContext
}

// ServiceContext is the service context for evaluation
type ServiceContext struct {
	ServiceName    string
	ServiceVersion string
	InstanceId     string
	Environment    string
	Metrics        map[string]string
}

// FlagEvaluationResponse is the response for EvaluateFlag
type FlagEvaluationResponse struct {
	FlagKey     string
	VariationId string
	RuleId      string
	Reason      *EvaluationReason
	Value       interface{}
}

// EvaluationReason is the reason for the evaluation result
type EvaluationReason struct {
	Type         string
	RuleId       string
	Description  string
	ErrorMessage string
}

// SetFlagRequest is the request for SetFlag
type SetFlagRequest struct {
	FlagKey       string
	Namespace     string
	Description   string
	Tags          map[string]string
	Temporary     bool
	ExpirationTime int64
	Version       string
	Value         interface{}
}

// SetFlagResponse is the response for SetFlag
type SetFlagResponse struct {
	Success bool
	Message string
	Version string
}

// FlagStreamRequest is the request for StreamFlagUpdates
type FlagStreamRequest struct {
	FlagKeys  []string
	Namespace string
}

// FlagUpdateEvent is an event for flag updates
type FlagUpdateEvent struct {
	EventType string
	FlagKey   string
	Namespace string
	Version   string
	Timestamp int64
	Value     interface{}
}

// ListFlagsRequest is the request for ListFlags
type ListFlagsRequest struct {
	Namespace  string
	Prefix     string
	TagFilter  string
	PageSize   int32
	PageToken  string
}

// ListFlagsResponse is the response for ListFlags
type ListFlagsResponse struct {
	Flags         []*FlagSummary
	TotalCount    int32
	NextPageToken string
}

// FlagSummary is a summary of a flag
type FlagSummary struct {
	FlagKey        string
	Namespace      string
	Description    string
	ValueType      string
	UpdatedAt      int64
	Temporary      bool
	ExpirationTime int64
	Tags           map[string]string
}

// HealthCheckRequest is the request for HealthCheck
type HealthCheckRequest struct {
	// Empty
}

// HealthCheckResponse is the response for HealthCheck
type HealthCheckResponse struct {
	Status  string
	Version string
	Details map[string]string
}

// FeatureFlagService_StreamFlagUpdatesServer is the server API for StreamFlagUpdates method.
type FeatureFlagService_StreamFlagUpdatesServer interface {
	Send(*FlagUpdateEvent) error
	grpc.ServerStream
}

